name: Auto Comment

on:
  issues:
    types: [opened, closed]
  pull_request_target:
    types: [closed, opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ğŸš§ Install
        run: |
          yarn

      - name: ğŸ“¦ Build
        run: |
          yarn build

      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: >
            ğŸ‘‹ @{{ author }}

            Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.

            Please make sure you have given us as much context as possible.

          issuesClosed: >
            ğŸ‘‹ @{{ author }} This issue is closed.

          pullRequestMerged: >
            ğŸ‘‹ @{{ author }} ğŸ‰ Congrats on your merged pull request! Thanks for the valuable contribution! ğŸ‘ğŸ‰ Congrats on your merged pull request! Thanks for the valuable contribution! ğŸ‘

          pullRequestOpened: >
            HelloğŸ‘‹ @{{ author }}, I hope you are doing well!
            <br>
            Thank you for raising your pull request and contributing to our Community ğŸ‰

            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.

          issuesAssigned: >
            Hello @{{ author }}, thank you for raising an issue. ğŸ™Œ I have assigned the issue to you. You can now start working on it. If you encounter any problems, please feel free to connect with us. ğŸ‘
